# NOTE: The versions can be updated by calling
#        pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [--line-length, "120"]
  - repo: https://github.com/ssciwr/clang-format-hook
    rev: v16.0.2
    hooks:
      - id: clang-format
        args: [-i]
  - repo: https://github.com/graphcore/examples-utils
    rev: v3.4
    hooks:
    - id: copyright-header-check
      args: [--amend]
