name: Run pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[all]
      - name: Test with pytest
        run: |
          pytest
  publish_report:
    runs-on: ubuntu-latest
    name: Publish Report
    needs: [build]
    if: always()
    outputs:
      summary: ${{ steps.output.outputs.summary }}
    steps:
      - name: Download Reports
        uses: actions/download-artifact@v3
      - name: Publish Summary
        id: publish_summary
        uses: mikepenz/action-junit-report@d507ab47ffeb036bd3671233143d8026470aa955 # v3.6.2 (pinned for security reasons)
        with:
          check_name: Report Summary
          report_paths: reports_${{ github.run_id }}/*report.xml