name: pytest

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: '0 2 * * *'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: graphcore/pytorch:latest
    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install . && pip install -r requirements-dev.txt
      - run: python -m pytest --cov --cov-report xml --junitxml=report.xml
      - uses: mikepenz/action-junit-report@d507ab47ffeb036bd3671233143d8026470aa955 # v3.6.2 (pinned for security reasons)
        if: always()
        with:
          report_paths: report.xml
