name: Run pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    outputs:
      summary: ${{ steps.output.outputs.summary }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r requirements-jupyter.txt
          pip install -r requirements-common.txt
      - name: Test with pytest
        run: |
          python -m pytest --junitxml=reports/pytest_report.xml
      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports_${{ github.run_id }}
          path: reports/*report.xml
      - name: Download Reports
        uses: actions/download-artifact@v3
      - name: Publish Summary
        id: publish_summary
        uses: mikepenz/action-junit-report@d507ab47ffeb036bd3671233143d8026470aa955 # v3.6.2 (pinned for security reasons)
        with:
          check_name: Report Summary
          report_paths: reports_${{ github.run_id }}/*report.xml